### PR TITLE
Fixed issue: Wrong time zone offset near DST boundaries

### LINKED ISSUE #93: Wrong time zone offset near DST boundaries
Take a look on the following example: 1 hour is lost in conversions.
Local time zone: GMT+0000 (Greenwich Mean Time)
Good hours: before 2:00 and after 7:00
Bad hours: between 2:00 and 7:00

import { zonedTimeToUtc, utcToZonedTime, format } from "date-fns-tz";

var nyTime = "2020-03-08 02:00:00"; // begin of the summer time: 2020-03-08T07:00:00.000Z
console.log("### nyTime = ", nyTime); // 2020-03-08 02:00:00 - local time in NY

var utcDate = zonedTimeToUtc(nyTime, "America/New_York");
console.log("### utcDate.toISOString() = ", utcDate.toISOString()); // lost 1 hour!: 2020-03-08T06:00:00.000Z

var d2 = utcToZonedTime(utcDate, "America/New_York");
var nyTime2 = format(d2, "yyyy-MM-dd HH:mm:ssX", {
  timeZone: "America/New_York"
});

// only after 7:00 offset changes to the summer time (local time zone is UTC)
console.log("### nyTime2 = ", nyTime2); // oops!: 2020-03-08 01:00:00-05

see https://codesandbox.io/s/heuristic-shtern-swg95?file=/src/index.js

Note #1: The local time zone was deliberately set to UTC in the Windows 10 Date & Time settings in order to eliminate the effect of the particular time zone.
Note #2: These transitions work fine in the luxon library, so the DST problem can be easily fixed by applying corresponding code from the luxon library.

### PR DESCRIPTION
**Pull request by marnusw**
Fixed Time Zone offset calculation. I think that this change will fix also a lot of other Time Zone related issues.
Closes #93

### CODE REVIEW

**Comment by marnusw** [comment]
@bsvetlik I've created this PR for your changes. It seems there are still some failing tests. I will look into these and hopefully we can get it merge soon.

**Comment by yharaskrik** [comment]
Hi, is there anything I can do to help move this along? I think we are running into an issue with DST.

When I do `formatTz(utcToZonedTime(date, timeZone), predefinedFormat, { timeZone })` with 1:30am UTC (`2021-03-14 01:30:00.000Z`) I receive 6:30pm in MST (Mountain Standard Time), this is right, but if I do the same thing with 2:30am UTC (`2021-03-14 02:30:00.000Z`) I get 8:30pm MST.

This happens on a server running in the cloud whos system clock is `UTC` as well as my local computer in `America/Vancouver`

**Comment by bsvetlik** [comment]
> Hi, is there anything I can do to help move this along? I think we are running into an issue with DST.
> 
> When I do `formatTz(utcToZonedTime(date, timeZone), predefinedFormat, { timeZone })` with 1:30am UTC (`2021-03-14 01:30:00.000Z`) I receive 6:30pm in MST (Mountain Standard Time), this is right, but if I do the same thing with 2:30am UTC (`2021-03-14 02:30:00.000Z`) I get 8:30pm MST.
> 
> This happens on a server running in the cloud whos system clock is `UTC` as well as my local computer in `America/Vancouver`

Hi Jay,

I am curious if my fix solved your issue too?

Thanks. Boris.

**Comment by yharaskrik** [comment]
Hey @bsvetlik, yes it did fix my issue.

Because we needed it in production i forked the repo, cherry picked your commit resolved the conflicts and update the tests and released our own version under `@trellisorg/data-fns-tz`. I will remove my package once this is fixed in the main repo.

**Comment by marnusw** [comment]
@yharaskrik will you please create a PR with passing tests? I will happily merge and release it. The only problem here was the failing tests and I haven't had time to investigate thoroughly.

**Comment by yharaskrik** [comment]
I sure can. I'll open a pr today

**Comment by yharaskrik** [comment]
https://github.com/marnusw/date-fns-tz/pull/108/files

**Comment by marnusw** [comment]
Merged as part of #108. See v1.1.2

**Pull request closed without merging**
