### PR TITLE
date-fns v4.1.0 support

### PR DESCRIPTION
**Pull request by eshimischi**

### CODE REVIEW

**Comment by eshimischi** [comment]
@marnusw let's do it when you'll time, thanks in advanced!

**Comment by eshimischi** [comment]
@marnusw thanks for merging! Would you please publish a new version of library to npm?

**Comment by marnusw** [comment]
Ran out of time this morning. I will. 👍🏻

**Comment by eshimischi** [comment]
> Ran out of time this morning. I will. 👍🏻

Tyt!

**Comment by eshimischi** [comment]
> Ran out of time this morning. I will. 👍🏻

Not published yet? https://www.npmjs.com/package/date-fns-tz v3.1.3

**Comment by marnusw** [comment]
`v3.2.0`

**Comment by markedwards** [comment]
Just to confirm -- this maintains backwards-compatibility with date-fns 3.x?

**Comment by eshimischi** [comment]
> Just to confirm -- this maintains backwards-compatibility with date-fns 3.x?

No. You should you use previous version v3.1.3

**Comment by markedwards** [comment]
> > Just to confirm -- this maintains backwards-compatibility with date-fns 3.x?
> 
> No. You should you use previous version v3.1.3

Thanks!  Probably a good idea to put this in the release notes.

**Comment by markedwards** [comment]
@marnusw so you're saying 3.2.0 does still support date-fns 3.x?  And @eshimischi is incorrect?

**Comment by markedwards** [comment]
Got it, thanks for the clarification.

**Pull request merged**
