### PR TITLE
Adds tests and CI config

### PR DESCRIPTION
**Pull request by grrowl**
* You'll need to log into https://travis-ci.org/ and activate it for this repo
* The new `src/_lib/tzParseTimezone/test.js` tests might be passing now
* The big concern on my branch was the tests here — https://github.com/grrowl/date-fns-tz/blob/ci/src/zonedTimeToUtc/test.js#L77-L105; we got it working until midnight, but midnight–2am was incorrectly converting from daylight savings hours (which didn't start till 2am). The changes on master have probably fixed this!

### CODE REVIEW

**Comment by grrowl** [comment]
Only one test is failing in `TZ="Australia/Melbourne"` https://travis-ci.org/github/grrowl/date-fns-tz/builds/733851333

**Comment by grrowl** [comment]
Re-enabled the skipped test introduced in this PR but no bueno: https://travis-ci.org/github/grrowl/date-fns-tz/jobs/733852430

**Comment by grrowl** [comment]
Happy to generate and refactor the DST change tests once this is in, we should have AEST -> AEDT (Australia/Melbourne), AEDT -> AEST and PST -> PDT, PDT -> PST coverage for `toDate`, `utcToZonedTime`, `zonedTimeToUtc`, and `tzParseTimezone`; even if these tests are skipped initially so we can work toward robustness.

Our application relying on this is expanding to the US either before or after 1st November so we're quite motivated to ensure these cases are covered 😅 thanks!

**Comment by marnusw** [comment]
Thanks for pulling this together @grrowl. Things seems to be working in the Western hemisphere, but not in Australia as you've pointed out above. I'd welcome the refactorings you're referring to. At least we can track the CI on PRs now, and I'll merge your work timeously. And if I can't keep up I'll give you access to the repo sooner rather than later.

**Pull request merged**
