### PR TITLE
Correctly consider local time zone

### PR DESCRIPTION
**Pull request by constgen**
Fixes https://github.com/marnusw/date-fns-tz/issues/44
Fixes https://github.com/marnusw/date-fns-tz/issues/31

### CODE REVIEW

**Comment by marnusw** [comment]
Thank you. I'm extremely busy at the moment but will endeavour to review soon.

**Comment by constgen** [comment]
@marnusw Lets review this. It will really help to a lot of devs

**Comment by dcousens** [comment]
@constgen could you please review https://github.com/marnusw/date-fns-tz/pull/46 ?
Either way,  it looks like we both need to add some tests for `utcToZonedTime`.

**Comment by constgen** [comment]
@dcousens There are 2 facts I noticed about this project
1. Testing infrastructure is broken. It fails when run locally and it is not setup to run on CI. So there is no chance to test PR
2. Certain time zones of the system are not considered in the test. So all test run on UTC system time zone which doesn't cover many issues that we faced.

Workaround. I personally use my patch locally until this PR is merged. You can too

```js
import tzParseTimezone from 'date-fns-tz/_lib/tzParseTimezone';

// fixed version of 'date-fns-tz/utcToZonedTime'
function utcToZonedTime (dirtyDate, tz, options) {
	let date = toDate(dirtyDate, options);

	// We just need to apply the offset indicated by the time zone to this localized date
	let offsetMilliseconds = tzParseTimezone(tz, date);
	let zonedDate = offsetMilliseconds ? subMilliseconds(date, offsetMilliseconds) : date;

	// This date has the UTC time values of the zoned date at the system time zone
	return new Date(
		zonedDate.getUTCFullYear(),
		zonedDate.getUTCMonth(),
		zonedDate.getUTCDate(),
		zonedDate.getUTCHours(),
		zonedDate.getUTCMinutes(),
		zonedDate.getUTCSeconds(),
		zonedDate.getUTCMilliseconds()
	 );
}
```

**Comment by constgen** [comment]
@marnusw lets review and merge it. This will really help to many dev

**Comment by fgblomqvist** [comment]
@constgen How is your fix different from #80 and #46? I think getting some clarity in which PRs are simply fixing the same thing would help in knowing which ones to close and which ones to merge.

**Comment by grrowl** [comment]
In case it's of use to anyone, I've published #46 and #51, added tests and [fixed the CI pipeline](https://travis-ci.org/github/grrowl/date-fns-tz/builds) as @mr-yum/date-fns-tz@1.1.0, [the repo is here](https://github.com/grrowl/date-fns-tz). I intend to maintain this fork and would love pull requests if anyone contribute tests or fixes to the project.

**Comment by fgblomqvist** [comment]
Thanks for the effort @grrowl!
I actually just spoke with the maintainer a day or two ago and he said he'd try to get around to taking a look at some of the PRs this weekend. If that doesn't happen, he was open to perhaps letting someone else aid with the maintenance. Maybe you could become a second maintainer? Obviously up to @marnusw. Would be wonderful if we could have a single repo/published package.

**Comment by grrowl** [comment]
I look forward to it! All that matters is that we have a reliable and lightweight date library which handles the (obviously tricky) job of handling timezone conversions. If @marnusw wants a hand maintaining this repo/package I am more than happy to help. The work is supported by my employer since we're all-in on date-fns on both client and server sides.

**Comment by marnusw** [comment]
Closed in #80, thank you though. Please reopen if your original issue persists.

**Comment by marnusw** [comment]
@grrowl thank you for offering to help out with the maintenance of this library. If you have the time what will help most right now is a PR for the CI setup that you've done, and I could also use some help seeing how many of the open issues are truly bugs vs. misunderstandings of how the library works.

Once we have the library bug free (and it only does so much... so we should manage to get there soon I'd hope when DST has been well tested) then we can consider how we move forward with work on a v2 API for the library.

**Comment by grrowl** [comment]
The irony, I got slammed with other work; will put up a PR with my changes minus the things you've fixed on master soon. Especially interested in testing the DST changeovers for a few key locales (Australia/Melbourne, America/Los_Angeles and perhaps Europe/London which changes over at 1am instead of 2am) :)

**Pull request closed without merging**
