### PR TITLE
Adding a error object to the catch of isValidTimezoneIANAString

### PR DESCRIPTION
**Pull request by ygormagalhaes**
A fix for the issue https://github.com/marnusw/date-fns-tz/issues/130

### CODE REVIEW

**Comment by X7Becka** [comment]
For what...?

**Comment by ygormagalhaes** [comment]
For the addition of the error object in the catch at src/_lib/tzParseTimezone/index.js # isValidTimezoneIANAString which is breaking applications running in Node 8 for example.

**Comment by marnusw** [comment]
You're right, I'm not sure how far back support for omitting the error goes but it is a relatively new feature. I'm happy to add this, thanks.

**Comment by marnusw** [comment]
`1.1.6`

**Pull request merged**
